### ISSUE TITLE
Profile tubular for slow operations

### ISSUE THREAD

**Issue by adamsardar** [azukds/tubular#182]
**What**

Find out where execution time (and memory allocations) are being spent in tubular processes.

**Why**

> Premature optimization is the root of all evil (Donald Knuth)

Several suggestions have been made to improve performance in tubular (e.g. #181), but without any kind of metric to measure where time is being spent or thinking about _how_ to measure performance gains these efforts are doomed to fail.

**How**

Find some examples from the docs/examples and then time how long execution is taking (and how much memory is being allocated/reallocated). Consider using [timeit](https://docs.python.org/3/library/timeit.html) for timing and [memray](https://github.com/bloomberg/memray) for memory (linux only).

_Definition of done_ would look like some flamegraphs across realistic examples.

**References**
- [Premature Optimization](https://wiki.c2.com/?PrematureOptimization)
- [Fast csv writing for R](https://h2o.ai/blog/2016/fast-csv-writing-for-r/) a great case-study in how to optimise a library whilst profiling
- [THE FALLACY OF PREMATURE OPTIMIZATION](https://ubiquity.acm.org/article.cfm?id=1513451#:~:text=Trying%20to%20do%20the%20optimization,best%20practice%20among%20software%20engineers.)

**Comment by limlam96** [comment]
Will summarise some results of this below, and set up issues separately. Just dug into the worst performing transformers initially:
1.  LogTransformer
- The numeric check here is quite slow, suspect it could be made more efficient (if it's actually needed at all?)
- Dropping the original column is also quite slow, should look into alternatives

2. OneHotEncoder

- Sklearn implementation is quite slow, and apparently pd.get_dummies is preferable:
https://stackoverflow.com/questions/53907202/why-is-sklearn-preprocessing-onehotencoder-so-slow
- The concat operation is quite slow, should look into alternatives

3. ArbitraryImputer

- Digging into this, fillna is called both in the base and child transformer, so that one is a bug and an easy fix
- fillna is generally quite slow, suggested alt here https://stackoverflow.com/questions/57954550/any-quicker-way-than-pandas-fillna

4. CappingTransformer

- Copy shows up among slowest parts, believe Lorna is working on removing these.
- Again the type check is quite slow, improve/remove

Also looked at fubular profiling, here the slowest parts are by far the copy creations (60-90% transformer runtime!), so worth looking to remove/improve. Worth highlighting, the improvements mentioned here are not near the scale of the improvement removing copies would have on fubular, so these are not going to bring us in range of fubular.
